# Generated by Django 4.2.1 on 2023-05-25 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, verbose_name='Product Name')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(299), django.core.validators.MaxValueValidator(499)], verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_email', models.EmailField(max_length=254, null=True, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('session_id', models.CharField(max_length=200, null=True)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.product', verbose_name='Product')),
            ],
        ),
    ]
