# Generated by Django 4.2.1 on 2023-06-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_content_alter_blog_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
