# Generated by Django 4.2.1 on 2023-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
